### ISSUE TITLE
SyntaxError: Unexpected token = during npm start

### ISSUE THREAD

**Issue by akashkj** [Stremio/stremio-web#251]
Getting following error when doing npm start

```
# npm start

> stremio@5.0.0 start /stremio-web
> webpack serve --mode development

<i> [webpack-dev-server] Generating SSL certificate...
<i> [webpack-dev-server] SSL certificate: /stremio-web/node_modules/.cache/webpack-dev-server/server.pem
10% building 0/1 entries 0/0 dependencies 0/0 modules[webpack-cli] /stremio-web/node_modules/webpack-dev-server/lib/servers/WebsocketServer.js:10
  static heartbeatInterval = 1000;
                           ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Server.getServerTransport (/stremio-web/node_modules/webpack-dev-server/lib/Server.js:1049:28)
    at Server.createWebSocketServer (/stremio-web/node_modules/webpack-dev-server/lib/Server.js:1612:38)
    at Server.start (/stremio-web/node_modules/webpack-dev-server/lib/Server.js:2176:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! stremio@5.0.0 start: `webpack serve --mode development`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the stremio@5.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-11-14T09_19_02_117Z-debug.log
```

npm install output

```
# npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})

added 1110 packages from 505 contributors and audited 1112 packages in 17.927s

120 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

Docker container info
```
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by akashkj** [comment]
Based on this - https://github.com/VickScarlet/lifeRestart/issues/176

After upgrading node version, error is resolved. 
Old version: v10.19.0
New version: v16.13.0

Maybe doc can be updated?
