### ISSUE TITLE
error when entering npm start

### ISSUE THREAD

**Issue by ket0x4** [Stremio/stremio-web#253]
``` agalar@ubuntu:~/stremio-web$ npm start

> stremio@5.0.0 start /home/agalar/stremio-web
> webpack serve --mode development

<i> [webpack-dev-server] SSL certificate: /home/agalar/stremio-web/node_modules/.cache/webpack-dev-server/server.pem
10% building 0/1 entries 0/0 dependencies 0/0 modules[webpack-cli] /home/agalar/stremio-web/node_modules/webpack-dev-server/lib/servers/WebsocketServer.js:10
  static heartbeatInterval = 1000;
                           ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Server.getServerTransport (/home/agalar/stremio-web/node_modules/webpack-dev-server/lib/Server.js:1049:28)
    at Server.createWebSocketServer (/home/agalar/stremio-web/node_modules/webpack-dev-server/lib/Server.js:1612:38)
    at Server.start (/home/agalar/stremio-web/node_modules/webpack-dev-server/lib/Server.js:2176:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! stremio@5.0.0 start: `webpack serve --mode development`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the stremio@5.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/agalar/.npm/_logs/2021-11-18T16_55_01_796Z-debug.log
agalar@ubuntu:~/stremio-web$```

**Comment by ket0x4** [comment]
Okay fixed after installing nodejs 14.x
