### ISSUE TITLE
[Bug] Stremio web doesn't load

### ISSUE THREAD

**Issue by NicolaSpadari** [Stremio/stremio-web#490]
Once I open the Stremio web version (web.stremio.com), the site won't load anything.
In console there's a React dom related error, probably blocking the page render:

```
react-dom.production.min.js:189 TypeError: Cannot read properties of null (reading 'off')
    at App.js:150:37
    at ZE (react-dom.production.min.js:240:251)
    at ts (react-dom.production.min.js:244:163)
    at m_ (react-dom.production.min.js:285:328)
    at react-dom.production.min.js:282:391
    at p (scheduler.production.min.js:13:203)
    at MessagePort.y (scheduler.production.min.js:14:128)
lE @ react-dom.production.min.js:189
react-dom.production.min.js:127 Uncaught TypeError: Cannot read properties of null (reading 'off')
    at App.js:150:37
    at ZE (react-dom.production.min.js:240:251)
    at ts (react-dom.production.min.js:244:163)
    at m_ (react-dom.production.min.js:285:328)
    at react-dom.production.min.js:282:391
    at p (scheduler.production.min.js:13:203)
    at MessagePort.y (scheduler.production.min.js:14:128)
react-dom.production.min.js:189 TypeError: Cannot read properties of null (reading 'off')
    at App.js:150:37
    at ZE (react-dom.production.min.js:240:251)
    at ts (react-dom.production.min.js:244:163)
    at m_ (react-dom.production.min.js:284:388)
    at react-dom.production.min.js:282:391
    at p (scheduler.production.min.js:13:203)
    at MessagePort.y (scheduler.production.min.js:14:128)
lE @ react-dom.production.min.js:189
react-dom.production.min.js:127 Uncaught TypeError: Cannot read properties of null (reading 'off')
    at App.js:150:37
    at ZE (react-dom.production.min.js:240:251)
    at ts (react-dom.production.min.js:244:163)
    at m_ (react-dom.production.min.js:284:388)
    at react-dom.production.min.js:282:391
    at p (scheduler.production.min.js:13:203)
    at MessagePort.y (scheduler.production.min.js:14:128)
VM14:25 Uncaught TypeError: Cannot read properties of null (reading 'prepend')
    at <anonymous>:25:12
```

![Screenshot 2023-10-19 at 23 38 27](https://github.com/Stremio/stremio-web/assets/25949931/809b09fa-1d3b-4d5c-9188-0733a7bffdd5)

web.strem.io works fine.

**Comment by unclekingpin** [comment]
Hi, the root cause of this is the serialization error, there could be something in your library that does not follow the schema, there shouldve been a separate screeen for that one. I will check
@NicolaSpadari Does that error happen on every page?

**Comment by NicolaSpadari** [comment]
Yes, happens of every page.
But as I said, the other website (web.strem.io) works just fine. In both I am logged in.
Is there any difference between the two? Which one should the user use? Or are they the same?

**Comment by TRtomasz** [comment]
@NicolaSpadari  you can try clearing local storage for web.stremio.com

**Comment by NicolaSpadari** [comment]
Yup, that works, thank you!
