### ISSUE TITLE
Streaming server crashes when using HTTPS on Windows

### ISSUE THREAD

**Issue by Valink16** [Stremio/stremio-web#497]
When going in the browser with https enabled (the certificate isn't even trusted but that's an other problem) and playing a movie/episode, the desktop app throws an error message:

```Stremio streaming server has thrown an error 
QProcess::ProcessError code: 1

(node:11972) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `stremio-runtime --trace-deprecation ...` to show where the warning was created)
C:\Users\valut\AppData\Local\Programs\LNV\Stremio-4\server.js:35949
                var code = error ? 500 : 200, body = JSON.stringify({
                                                          ^

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    --- property 'issuerCertificate' closes the circle
    at JSON.stringify (<anonymous>)
    at C:\Users\valut\AppData\Local\Programs\LNV\Stremio-4\server.js:35949:59
    at C:\Users\valut\AppData\Local\Programs\LNV\Stremio-4\server.js:26985:52
    at C:\Users\valut\AppData\Local\Programs\LNV\Stremio-4\server.js:59595:29
    at ClientRequest.<anonymous> (C:\Users\valut\AppData\Local\Programs\LNV\Stremio-4\server.js:27552:25)
    at ClientRequest.f (C:\Users\valut\AppData\Local\Programs\LNV\Stremio-4\server.js:6431:70)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:486:12)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:486:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:8616) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `stremio-runtime --trace-deprecation ...` to show where the warning was created)
C:\Users\valut\AppData\Local\Programs\LNV\Stremio-4\server.js:35949
                var code = error ? 500 : 200, body = JSON.stringify({
                                                          ^

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    --- property 'issuerCertificate' closes the circle
    at JSON.stringify (<anonymous>)
    at C:\Users\valut\AppData\Local\Programs\LNV\Stremio-4\server.js:35949:59
    at C:\Users\valut\AppData\Local\Programs\LNV\Stremio-4\server.js:26985:52
    at C:\Users\valut\AppData\Local\Programs\LNV\Stremio-4\server.js:59595:29
    at ClientRequest.<anonymous> (C:\Users\valut\AppData\Local\Programs\LNV\Stremio-4\server.js:27552:25)
    at ClientRequest.f (C:\Users\valut\AppData\Local\Programs\LNV\Stremio-4\server.js:6431:70)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:486:12)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:486:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by beardedhog** [comment]
I get the same error on Windows. The same unresolved issue on macOS was reported in Stremio/stremio-bugs#472. Any advice on this?

**Comment by JoaoMXN** [comment]
Same here.

Windows 11 on Edge.
